In [1]:
import pandas as pd

In [ ]:
# 2 main Data types in Pandas 
# 1. Series     : 1 Dimensional
# 2. Dataframe  : 2 Dimensional

series = pd.Series(["Apple","Banana","Orange"])
print(series)

0     Apple
1    Banana
2    Orange
dtype: str

In [4]:
df = pd.DataFrame({
    "fruits" : ["Apple","Banana","Mango","Orange"],
    "colors" : ["Red","Yellow","Yellow","Orange"]
})

df

   fruits  colors
0   Apple     Red
1  Banana  Yellow
2   Mango  Yellow
3  Orange  Orange

In [5]:
car_sales = pd.read_csv('car-sales.csv')
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [7]:
# Exporting a dataset 
car_sales.to_csv("car-sales-exported.csv",index=False)

## Describing Data In Pandas

In [8]:
car_sales.dtypes

Make               str
Colour             str
Odometer (KM)    int64
Doors            int64
Price              str
dtype: object

In [9]:
car_sales.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='str')

In [10]:
car_sales.index

RangeIndex(start=0, stop=10, step=1)

In [11]:
car_sales.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [12]:
car_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     str
 1   Colour         10 non-null     str
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     str
dtypes: int64(2), str(3)
memory usage: 532.0 bytes

In [14]:
car_sales.mean(numeric_only=True)

Odometer (KM)    78601.4
Doors                4.0
dtype: float64

In [15]:
car_sales["Doors"].sum()

np.int64(40)

In [16]:
len(car_sales)

10

## Viewing and Selecting Data